baseURL = "https://srininidhi-blogs.netlify.app/"
languageCode = "en-us"
title = "Srinidhi's Blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Srinidhi Bhat"
  description = "In solitude, where we are least alone."
  github = "srinidhibhat45"
  twitter = "YourFatGuy"
  linkedin = "srinidhi-bhat-8aaa2a147/"
  instagram = "shrxnxhdx"
  email = "srinidhibhat45@gmail.com"
  url = "srinidhibhat.netlify.app"
  keywords = "blog, srinidhi bhat"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "India"

  [[params.links]]
    title = "Link"
    href = "srinidhibhat.netlify.app"
  [[params.links]]
    title = "Link2"
    href = "http://srinidhibhat.netlify.app"
    icon = "static/images/favicon.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
